### ISSUE TITLE
Serial Print baud rate?

### ISSUE THREAD

**Issue by jbobrow** [bigjosh/Move38-Arduino-Platform#79]
Serial printing is not functioning as expected. There is communication but it isn't showing up on screen as the characters that are being sent.

**Comment by bigjosh** [comment]
Not a baud rate issue, a stack blown issue! 

Looks like stack was crashing into strings and overwriting them with garbage. 

Note that it is a good idea to always use `F("THis is a string)")` for immutable strings. This keeps them in flash rather than wasting ram and avoids problems like this...

https://www.arduino.cc/reference/en/language/variables/utilities/progmem/#_the_code_f_code_macro
